/*
 * sl6806_romclk.h - GENERATED by tools/sl6806-romclocks. Do not edit.
 *
 * The mask ROM's second clock family, from the dispatcher at ROM
 * 0x20EC. 15b's 128 module ids are one mechanism; these are
 * another, and nothing in this project had touched them until the
 * camera's sensor_init turned out to call id 58.
 *
 * Transcribed rather than called: the veneer the application uses
 * (0x008051EC) is not resident in bootloader mode, and each entry
 * is one OR into one register, which is trivial to perform here.
 *
 * WHAT EACH ONE CLOCKS IS UNKNOWN. Two are attributed: 58 is the
 * camera sensor's (0x00D44CD8) and 73 sets CRU +0x118, which is
 * also the camera module clock 0x00D44688 programs. The rest are a
 * map with no legend - which is exactly what the module ids were
 * before they were walked.
 *
 * Regenerate with:
 *     tools/sl6806-romclocks maskrom.bin \
 *         --header cores/sl6806/sl6806_romclk.h
 */
#ifndef SL6806_ROMCLK_H
#define SL6806_ROMCLK_H

#include <stdint.h>

typedef struct {
    uint8_t  id;
    uint32_t addr;
    uint32_t bit;
} sl6806_romclk_t;

#define SL6806_ROMCLK_COUNT  56

static const sl6806_romclk_t sl6806_romclk[] = {
    {  0, 0x40080030u, 0x00010000u },
    {  2, 0x40080030u, 0x00010000u },
    {  8, 0x40080030u, 0x00000020u },
    {  9, 0x40080030u, 0x00000040u },
    { 17, 0x40080080u, 0x00000001u },
    { 18, 0x400800ACu, 0x00000001u },
    { 19, 0x40080088u, 0x00000001u },
    { 20, 0x40080090u, 0x00000001u },
    { 21, 0x400800B0u, 0x00000001u },
    { 22, 0x400800B4u, 0x00000001u },
    { 23, 0x400800C4u, 0x00000001u },
    { 25, 0x400800D0u, 0x00000001u },
    { 26, 0x400800D4u, 0x00000001u },
    { 27, 0x400800DCu, 0x00000001u },
    { 28, 0x400800E4u, 0x00000001u },
    { 29, 0x400800E8u, 0x00000001u },
    { 30, 0x400800ECu, 0x00000001u },
    { 32, 0x400800F0u, 0x00000001u },
    { 34, 0x400800D8u, 0x00000001u },
    { 35, 0x400800E0u, 0x00000001u },
    { 36, 0x400800B8u, 0x00000001u },
    { 37, 0x400800A8u, 0x00000001u },
    { 38, 0x400800FCu, 0x00000001u },
    { 39, 0x400800F4u, 0x00000001u },
    { 40, 0x400800F8u, 0x00000001u },
    { 41, 0x40080030u, 0x00000010u },
    { 42, 0x40080030u, 0x00010000u },
    { 43, 0x400800A0u, 0x00000001u },
    { 44, 0x40080094u, 0x00000001u },
    { 48, 0x4008009Cu, 0x00000001u },
    { 50, 0x400800C8u, 0x00000001u },
    { 51, 0x40080098u, 0x00000001u },
    { 52, 0x40080100u, 0x00000001u },
    { 53, 0x40080030u, 0x00010000u },
    { 54, 0x40080104u, 0x00000001u },
    { 56, 0x4008008Cu, 0x00000001u },
    { 57, 0x4008008Cu, 0x00010000u },
    { 58, 0x400800C0u, 0x00000001u },
    { 60, 0x400F1000u, 0x00000001u },
    { 61, 0x40080108u, 0x00000001u },
    { 63, 0x4008010Cu, 0x00000001u },
    { 65, 0x40080084u, 0x00000001u },
    { 66, 0x40080110u, 0x00000001u },
    { 71, 0x4008001Cu, 0x00010000u },
    { 72, 0x40080114u, 0x00000001u },
    { 73, 0x40080118u, 0x00000001u },
    { 74, 0x4008011Cu, 0x00000001u },
    { 75, 0x40080120u, 0x00000001u },
    { 77, 0x400F1040u, 0x00000001u },
    { 78, 0x400F1044u, 0x00000001u },
    { 79, 0x400F1048u, 0x00000001u },
    { 80, 0x400F1050u, 0x00000001u },
    { 81, 0x400F1054u, 0x00000001u },
    { 82, 0x400F1058u, 0x00000001u },
    { 83, 0x400F105Cu, 0x00000001u },
    { 84, 0x400F1000u, 0x00000002u },
};

/* [V] The one the camera sensor's own init enables. */
#define SL6806_ROMCLK_SENSOR  58

#endif /* SL6806_ROMCLK_H */
