/*
 * panel.c - display definition for the P20 Player.
 *
 * The panel is fully described here. Geometry, colour format, the vendor
 * initialisation sequence and the sleep/wake/on/off sequences were all
 * recovered from the stock firmware, and every table below can be
 * regenerated from a dump:
 *
 *     tools/sl6806-panelseq dump.bin        # readable listing
 *     tools/sl6806-panelseq dump.bin --c    # exactly the tables below
 *
 *   240 x 296 visible, drawn at controller offset (0, 12)
 *   COLMOD 0x55 = RGB565, MADCTL 0x00, display inversion on
 *   33 vendor commands, ending INVON / SLPOUT / 120 ms / DISPON / 50 ms
 *
 * The byte-level transport - the last thing that was missing - is the LCD
 * controller at 0x400D9000, driven as a QSPI master. It lives in
 * cores/sl6806/sl6806_lcdc.c, and this board's half of it (pads, module
 * clock, lane map) is in lcdc.c next door. sl6806_panel_get() brings it up
 * on first use, so a sketch needs nothing but Screen.begin().
 *
 * A board that wants a different transport registers its own before touching
 * Screen:
 *
 *     sl6806_lcd_bus_register(&my_bus);
 *     Screen.begin();
 *
 * If no bus comes up, sl6806_panel_get() still returns NULL, because a panel
 * whose flush did nothing would make Display::available() claim success and
 * then silently drop every frame.
 *
 * ---------------------------------------------------------------------
 * HOW THIS WAS FOUND (so it can be re-checked or extended)
 *
 * The panel descriptor lives in flash at 0x00C519FC and is copied to SRAM at
 * 0x0081C1CC. sl6806-panelseq finds it by signature rather than by address:
 * bytes +0x0F..+0x13 are 0x2C 0x2E 0x2A 0x2B 0x36 - RAMWR, RAMRD, CASET,
 * RASET, MADCTL - and the five words at +0x14 are Thumb pointers into the XIP
 * window. Exactly one candidate in the image matches. Layout, verified:
 *
 *   +0x00 u16  240      width
 *   +0x02 u16  296      height
 *   +0x04 u16  0        x offset
 *   +0x06 u16  12       y offset
 *   +0x08 u8   1        colour mode: 1 = RGB565, 2 = RGB888
 *   +0x0A u8   2        display rotation index
 *   +0x0C u8   50       0x32, the QSPI four-lane write opcode (pixels)
 *   +0x0D u8   2        0x02, the QSPI one-lane write opcode (commands)
 *   +0x0E u8   0x0B
 *   +0x0F u8   0x2C     RAMWR
 *   +0x10 u8   0x2E     RAMRD
 *   +0x11 u8   0x2A     CASET
 *   +0x12 u8   0x2B     RASET
 *   +0x13 u8   0x36     MADCTL
 *   +0x14 ptr  0x00D3F46D   init
 *   +0x18 ptr  0x00D3F8CD   sleep
 *   +0x1C ptr  0x00D3F8F9   wake
 *   +0x20 ptr  0x00D3F941   display on
 *   +0x24 ptr  0x00D3F925   display off
 *
 * The init sequence is not stored as a table in the firmware: it is open
 * coded as ~150 calls to the two writer routines, with the byte to send as
 * an immediate in each call. sl6806-panelseq disassembles that back into the
 * table below. The controller answers the standard DCS commands but has a
 * large vendor register set (0x61-0x68, 0xB1-0xB6, 0xDF-0xEC, 0xF1-0xF6),
 * so it is a vendor variant rather than a stock ST7789.
 */

#include "gfx/Panel.h"
#include "variant.h"

/* ---------------------------------------------------------------------
 * Generated by tools/sl6806-panelseq from the reference 4 MiB dump.
 * Descriptor at 0x00C519FC; command writer 0x0080E842, data writer
 * 0x0080E8D8. Do not hand-edit: regenerate instead.
 * ------------------------------------------------------------------ */

static const uint8_t panel_init[] = {
    SL6806_LCD_CMD, 0xFD, 2, 0x06, 0x08,
    SL6806_LCD_CMD, 0x61, 2, 0x07, 0x04,
    SL6806_LCD_CMD, 0x62, 3, 0x00, 0x44, 0x40,
    SL6806_LCD_CMD, 0x63, 4, 0x41, 0x07, 0x12, 0x12,
    SL6806_LCD_CMD, 0x64, 1, 0x37,
    SL6806_LCD_CMD, 0x65, 3, 0x09, 0x10, 0x21,
    SL6806_LCD_CMD, 0x66, 3, 0x09, 0x10, 0x21,
    SL6806_LCD_CMD, 0x67, 2, 0x21, 0x40,
    SL6806_LCD_CMD, 0x68, 4, 0x9C, 0x30, 0x21, 0x27,
    SL6806_LCD_CMD, 0xB1, 3, 0x0F, 0x02, 0x02,
    SL6806_LCD_CMD, 0xB4, 1, 0x01,
    SL6806_LCD_CMD, 0xB5, 4, 0x02, 0x02, 0x0A, 0x14,
    SL6806_LCD_CMD, 0xB6, 5, 0x04, 0x01, 0x9F, 0x00, 0x02,
    SL6806_LCD_CMD, 0xDF, 1, 0x11,
    SL6806_LCD_CMD, 0xE2, 6, 0x23, 0x1D, 0x1E, 0x2F, 0x30, 0x3F,
    SL6806_LCD_CMD, 0xE5, 6, 0x3F, 0x30, 0x2F, 0x1E, 0x23, 0x22,
    SL6806_LCD_CMD, 0xE1, 2, 0x25, 0x6B,
    SL6806_LCD_CMD, 0xE4, 2, 0x6C, 0x25,
    SL6806_LCD_CMD, 0xE0, 8, 0x05, 0x05, 0x10, 0x0E, 0x10, 0x0F, 0x13, 0x18,
    SL6806_LCD_CMD, 0xE3, 8, 0x18, 0x13, 0x0F, 0x0F, 0x10, 0x09, 0x07, 0x05,
    SL6806_LCD_CMD, 0xE6, 2, 0x00, 0xFF,
    SL6806_LCD_CMD, 0xE7, 6, 0x01, 0x04, 0x03, 0x03, 0x00, 0x12,
    SL6806_LCD_CMD, 0xE8, 3, 0x00, 0x50, 0x00,
    SL6806_LCD_CMD, 0xEC, 1, 0x52,
    SL6806_LCD_CMD, 0xF1, 3, 0x01, 0x01, 0x02,
    SL6806_LCD_CMD, 0xF6, 4, 0x01, 0x30, 0x00, 0x00,
    SL6806_LCD_CMD, 0xFD, 2, 0xFA, 0xFC,
    SL6806_LCD_CMD, 0x3A, 1, 0x55,   /* COLMOD */
    SL6806_LCD_CMD, 0x35, 1, 0x00,   /* TEON */
    SL6806_LCD_CMD, 0x36, 1, 0x00,   /* MADCTL */
    SL6806_LCD_CMD, 0x21, 0,   /* INVON */
    SL6806_LCD_CMD, 0x11, 0,   /* SLPOUT */
    SL6806_LCD_DELAY, 120, 0,   /* 120 ms */
    SL6806_LCD_CMD, 0x29, 0,   /* DISPON */
    SL6806_LCD_DELAY, 50, 0,   /* 50 ms */
    SL6806_LCD_END,
};

static const uint8_t panel_sleep[] = {
    SL6806_LCD_CMD, 0x28, 0,   /* DISPOFF */
    SL6806_LCD_DELAY, 10, 0,   /* 10 ms */
    SL6806_LCD_CMD, 0x10, 0,   /* SLPIN */
    SL6806_LCD_DELAY, 120, 0,   /* 120 ms */
    SL6806_LCD_END,
};

static const uint8_t panel_wake[] = {
    SL6806_LCD_CMD, 0x11, 0,   /* SLPOUT */
    SL6806_LCD_DELAY, 120, 0,   /* 120 ms */
    SL6806_LCD_CMD, 0x29, 0,   /* DISPON */
    SL6806_LCD_DELAY, 10, 0,   /* 10 ms */
    SL6806_LCD_END,
};

static const uint8_t panel_display_on[] = {
    SL6806_LCD_CMD, 0x29, 0,   /* DISPON */
    SL6806_LCD_DELAY, 10, 0,   /* 10 ms */
    SL6806_LCD_END,
};

static const uint8_t panel_display_off[] = {
    SL6806_LCD_CMD, 0x28, 0,   /* DISPOFF */
    SL6806_LCD_DELAY, 10, 0,   /* 10 ms */
    SL6806_LCD_END,
};

/* --------------------------------------------------- end generated tables */

const sl6806_dcs_panel_t sl6806_p20_panel = {
    .width    = SL6806_PANEL_WIDTH,
    .height   = SL6806_PANEL_HEIGHT,
    .x_offset = SL6806_PANEL_X_OFFSET,
    .y_offset = SL6806_PANEL_Y_OFFSET,

    .caset = SL6806_DCS_CASET,
    .raset = SL6806_DCS_RASET,
    .ramwr = SL6806_DCS_RAMWR,

    .init        = panel_init,
    .sleep       = panel_sleep,
    .wake        = panel_wake,
    .display_on  = panel_display_on,
    .display_off = panel_display_off,

    /* The vendor reset pulse, from the panel reset routine at 0x00D3E1A4:
     * high / 10 ms / low / 20 ms / high / 120 ms. */
    .reset_high_ms   = 10,
    .reset_low_ms    = 20,
    .reset_settle_ms = 120,
};

static int p20_begin(void)
{
    return sl6806_dcs_begin(&sl6806_p20_panel);
}

static void p20_flush(int16_t x, int16_t y, int16_t w, int16_t h,
                      const sl6806_color_t *src)
{
    sl6806_dcs_flush(&sl6806_p20_panel, x, y, w, h, src);
}

static void p20_backlight(uint8_t level)
{
    const sl6806_lcd_bus_t *bus = sl6806_lcd_bus();

    if (bus && bus->backlight)
        bus->backlight(level);
}

static const sl6806_panel_t p20_panel = {
    .name      = "P20 240x296 RGB565",
    .width     = SL6806_PANEL_WIDTH,
    .height    = SL6806_PANEL_HEIGHT,
    .begin     = p20_begin,
    .flush     = p20_flush,
    .backlight = p20_backlight,
};

const sl6806_panel_t *sl6806_panel_get(void)
{
    /* Bring the LCD controller up on first use, so a sketch needs nothing
     * but Screen.begin(). On this board that lands in lcdc.c; in a host test,
     * which links this file but not that one, it is the weak no-op in
     * LcdBus.c and nothing touches a peripheral. */
    if (!sl6806_lcd_bus())
        sl6806_lcd_bus_autoinit();

    /* No transport, no panel. Reporting NULL here is what keeps
     * Display::available() honest. */
    return sl6806_lcd_bus() ? &p20_panel : 0;
}
